# Fix GitHub Actions CI workflow
# Run: Set-ExecutionPolicy Bypass -Scope Process -Force; .\CIFIX.ps1

$RepoPath = "C:\Users\LionelMosley\Documents\HTML\Synology - DiskStation Monitor"
Set-Location $RepoPath
$b64 = "bmFtZTogU2VjdXJpdHkKCm9uOgogIHB1c2g6CiAgICBicmFuY2hlczogW21haW5dCiAgcHVsbF9yZXF1ZXN0OgogICAgYnJhbmNoZXM6IFttYWluXQogIHNjaGVkdWxlOgogICAgLSBjcm9uOiAnMCA2ICogKiAxJwoKam9iczoKICBhdWRpdDoKICAgIG5hbWU6IERlcGVuZGVuY3kgQXVkaXQKICAgIHJ1bnMtb246IHVidW50dS1sYXRlc3QKICAgIHN0ZXBzOgogICAgICAtIHVzZXM6IGFjdGlvbnMvY2hlY2tvdXRAdjQKICAgICAgLSB1c2VzOiBhY3Rpb25zL3NldHVwLW5vZGVAdjQKICAgICAgICB3aXRoOgogICAgICAgICAgbm9kZS12ZXJzaW9uOiAnMjAnCiAgICAgIC0gbmFtZTogSW5zdGFsbCBkZXBlbmRlbmNpZXMKICAgICAgICBydW46IG5wbSBpbnN0YWxsIC0tbGVnYWN5LXBlZXItZGVwcwogICAgICAtIG5hbWU6IERlcGVuZGVuY3kgYXVkaXQgKGJhY2tlbmQpCiAgICAgICAgcnVuOiBjZCBiYWNrZW5kICYmIG5wbSBhdWRpdCAtLWF1ZGl0LWxldmVsPWhpZ2ggfHwgdHJ1ZQogICAgICAtIG5hbWU6IERlcGVuZGVuY3kgYXVkaXQgKGZyb250ZW5kKQogICAgICAgIHJ1bjogY2QgZnJvbnRlbmQgJiYgbnBtIGF1ZGl0IC0tYXVkaXQtbGV2ZWw9aGlnaCB8fCB0cnVlCgogIGJ1aWxkOgogICAgbmFtZTogQnVpbGQgQ2hlY2sKICAgIHJ1bnMtb246IHVidW50dS1sYXRlc3QKICAgIHN0ZXBzOgogICAgICAtIHVzZXM6IGFjdGlvbnMvY2hlY2tvdXRAdjQKICAgICAgLSB1c2VzOiBhY3Rpb25zL3NldHVwLW5vZGVAdjQKICAgICAgICB3aXRoOgogICAgICAgICAgbm9kZS12ZXJzaW9uOiAnMjAnCiAgICAgIC0gbmFtZTogSW5zdGFsbCBkZXBlbmRlbmNpZXMKICAgICAgICBydW46IG5wbSBpbnN0YWxsIC0tbGVnYWN5LXBlZXItZGVwcwogICAgICAtIG5hbWU6IEJ1aWxkIGJhY2tlbmQKICAgICAgICBydW46IG5wbSBydW4gYnVpbGQgLS13b3Jrc3BhY2U9YmFja2VuZAo="
$bytes = [System.Convert]::FromBase64String($b64)
$fullPath = Join-Path $RepoPath ".github\workflows\security.yml"
[System.IO.File]::WriteAllBytes($fullPath, $bytes)
Write-Host "  updated security.yml" -ForegroundColor Green
git add .github/workflows/security.yml
git commit -m "fix: CI workflow - remove lockfile requirement"
git push origin main
Write-Host "Done" -ForegroundColor Green