# Fix netlify.toml copy command
# Run: Set-ExecutionPolicy Bypass -Scope Process -Force; .\CPFIX.ps1

$RepoPath = "C:\Users\LionelMosley\Documents\HTML\Synology - DiskStation Monitor"
Set-Location $RepoPath
$b64 = "W2J1aWxkXQogIGJhc2UgICAgPSAiZnJvbnRlbmQiCiAgY29tbWFuZCA9ICJta2RpciAtcCBkaXN0ICYmIGNwIC1yIHB1YmxpYy8uIGRpc3QvIgogIHB1Ymxpc2ggPSAiZGlzdCIKCltidWlsZC5lbnZpcm9ubWVudF0KICBOT0RFX1ZFUlNJT04gPSAiMjAiCgpbW3JlZGlyZWN0c11dCiAgZnJvbSAgID0gIi8iCiAgdG8gICAgID0gIi9kc20tYXV0aC5odG1sIgogIHN0YXR1cyA9IDIwMAoKW1tyZWRpcmVjdHNdXQogIGZyb20gICA9ICIvZGFzaGJvYXJkIgogIHRvICAgICA9ICIvc3lub2xvZ3ktbW9uaXRvci5odG1sIgogIHN0YXR1cyA9IDIwMAoKW1tyZWRpcmVjdHNdXQogIGZyb20gICA9ICIvKiIKICB0byAgICAgPSAiL2RzbS1hdXRoLmh0bWwiCiAgc3RhdHVzID0gMjAwCgpbW2hlYWRlcnNdXQogIGZvciA9ICIvKiIKICBbaGVhZGVycy52YWx1ZXNdCiAgICBYLUZyYW1lLU9wdGlvbnMgICAgICAgICA9ICJERU5ZIgogICAgWC1Db250ZW50LVR5cGUtT3B0aW9ucyAgPSAibm9zbmlmZiIKICAgIFJlZmVycmVyLVBvbGljeSAgICAgICAgID0gInN0cmljdC1vcmlnaW4td2hlbi1jcm9zcy1vcmlnaW4iCiAgICBQZXJtaXNzaW9ucy1Qb2xpY3kgICAgICA9ICJjYW1lcmE9KCksIG1pY3JvcGhvbmU9KCksIGdlb2xvY2F0aW9uPSgpIgogICAgQ29udGVudC1TZWN1cml0eS1Qb2xpY3kgPSAiZGVmYXVsdC1zcmMgJ3NlbGYnOyBzY3JpcHQtc3JjICdzZWxmJyAndW5zYWZlLWlubGluZScgaHR0cHM6Ly9jZG5qcy5jbG91ZGZsYXJlLmNvbSBodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29tOyBzdHlsZS1zcmMgJ3NlbGYnICd1bnNhZmUtaW5saW5lJyBodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29tIGh0dHBzOi8vY2RuanMuY2xvdWRmbGFyZS5jb207IGZvbnQtc3JjICdzZWxmJyBodHRwczovL2ZvbnRzLmdzdGF0aWMuY29tOyBpbWctc3JjICdzZWxmJyBkYXRhOiBibG9iOiBodHRwczovLyoudGlsZS5vcGVuc3RyZWV0bWFwLm9yZyBodHRwczovLyouYmFzZW1hcHMuY2FydG9jZG4uY29tOyBjb25uZWN0LXNyYyAnc2VsZicgaHR0cHM6Ly9kaXNrc3RhdGlvbi1tb25pdG9yLXByb2R1Y3Rpb24udXAucmFpbHdheS5hcHAgaHR0cHM6Ly9ub21pbmF0aW0ub3BlbnN0cmVldG1hcC5vcmciCg=="
$bytes = [System.Convert]::FromBase64String($b64)
$fullPath = Join-Path $RepoPath "netlify.toml"
[System.IO.File]::WriteAllBytes($fullPath, $bytes)
Write-Host "  updated netlify.toml" -ForegroundColor Green
git add netlify.toml
git commit -m "fix: copy public contents not folder - use cp -r public/. dist/"
git push origin main
if ($LASTEXITCODE -eq 0) {
    Write-Host "`n Done! Visit: https://dsm.4thandbailey.com/synology-monitor.html" -ForegroundColor Green
} else {
    Write-Host "`n Push failed." -ForegroundColor Red
}